### ISSUE TITLE
binary: log level configuration

### ISSUE THREAD

**Issue by user9931** [anacrolix/dms#121]
Using it binary as dlna server with systemd and there's so many log messages like `<path_to_file> ignored: non-media file (text/x-ssa)` (subtitles and other related files). Is there's some setting that allows to turn those messages off (and not fill systemd journal)  but still log important ones, like actual errors? [now using grep -v "ignored" as workaround]

**Comment by anacrolix** [comment]
I'll look to lower the logging level on these.
