### ISSUE TITLE
ssdp panic while caltulating delay time

### ISSUE THREAD

**Issue by qzhsjz** [anacrolix/dms#123]
panic: invalid argument to Int63n

goroutine 3806 [running]:
math/rand.(*Rand).Int63n(0x140005d0140?, 0x14001058890?)
        /opt/homebrew/opt/go/libexec/src/math/rand/rand.go:121 +0xe8
math/rand.Int63n(...)
        /opt/homebrew/opt/go/libexec/src/math/rand/rand.go:348
github.com/anacrolix/dms/ssdp.(*Server).handle(0x140005d0140, {0x140012dd200, 0x65, 0x5dc}, 0x140005381b0?)
        /Users/***/go/pkg/mod/github.com/anacrolix/dms@v1.6.0/ssdp/ssdp.go:319 +0x874
created by github.com/anacrolix/dms/ssdp.(*Server).serve
        /Users/***/go/pkg/mod/github.com/anacrolix/dms@v1.6.0/ssdp/ssdp.go:129 +0x2c

**Comment by qzhsjz** [comment]
<img width="1720" alt="图片" src="https://github.com/anacrolix/dms/assets/10796024/4d256de7-c8ef-4192-a720-1a1a82221f56">
This is because some clients report the mx value 0.

**Comment by qzhsjz** [comment]
#124

**Comment by anacrolix** [comment]
Fixed by https://github.com/anacrolix/dms/pull/124, thank you very much for the contribution.
