### ISSUE TITLE
Panic on Close() function

### ISSUE THREAD

**Issue by tsynik** [anacrolix/dms#142]
@anacrolix, sometimes we have such error with TorrServer and DLNA enabled
```
2024/05/30 16:17:45 [Recovery] 2024/05/30 - 16:17:45 panic recovered:
close of closed channel
runtime/chan.go:365 (0x1f81b84)
github.com/anacrolix/dms@v1.6.0/dlna/dms/dms.go:1042 (0x26aa20f)
server/dlna/dlna.go:113 (0x26aa20a)
server/web/api/settings.go:49 (0x26aa1f8)
github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x25f20f9)
github.com/gin-gonic/gin@v1.10.0/recovery.go:102 (0x25f20e7)
github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x26b088b)
server/web/blocker/blocker.go:21 (0x26b0879)
github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x25e4c6a)
server/log/log.go:90 (0x276d364)
github.com/gin-gonic/gin@v1.10.0/context.go:185 (0x25f0e91)
github.com/gin-gonic/gin@v1.10.0/gin.go:633 (0x25f0900)
github.com/gin-gonic/gin@v1.10.0/gin.go:589 (0x25f0431)
net/http/server.go:3137 (0x22aeaad)
net/http/server.go:2039 (0x22a9d87)
runtime/asm_amd64.s:1695 (0x1fefca0)
```
probably after PC with running server restored from sleep (not sure).
This code produce it:
```
func Stop() {
	if dmsServer != nil {
		dmsServer.Close()
		dmsServer = nil
	}
}
```
is it a library bug or something on TorrServer side? Here is dmsServer implementation - https://github.com/YouROK/TorrServer/blob/master/server/dlna/dlna.go

**Comment by anacrolix** [comment]
After you call Close on the server, it's probably not safe to be using it anymore, particularly concurrently. It's like that you have a concurrency bug where you're still using it from another routine. You should synchronize access to the dms Server. I've used the pattern before where I have a RWMutex and require write access for destructive operations, and use RLock for everything else (in this case your gin-gonic handlers might take that).

**Comment by anacrolix** [comment]
👍🏻 did it work out for you?
