### ISSUE TITLE
Long UI "loading" times with LG LM7600 TV

### ISSUE THREAD

**Issue by mdempsky** [anacrolix/dms#32]
I'm experimenting with using dms to stream a single MKV/H264/AC3 video file from my OpenBSD mini-server to my LG LM7600 TV.  Video streaming seems successful (yay!), but while navigating the directory structure, my TV UI has very long "Loading..." pauses (about 20 seconds) every time it displays a directory, even though the directories are all tiny.

I don't experience the same pauses with Twonky media server running on my WD MyBook NAS drive, even with much larger directories.  The pauses also seem pretty consistent; e.g., they don't go away after an initial dms warmup or something.

I started poking into trying to find out where the latency might be, but I'm not very familiar with the UPnP/DLNA protocols.  I noticed there seem to be some /ctl HTTP requests around the pauses, but instrumenting serviceControlHandler I see it's finishing in less than a millisecond, so not likely the problem.

I'll continue digging into it, but thought I'd file an issue in case you have any ideas where I should look to explain the 20 second pauses.

**Comment by mdempsky** [comment]
Changing

```
    if r.UserAgent() == "" && true {
```

to

```
    if r.UserAgent() == "" && false {
```

in dlna/dms/dms.go seems to fix the pauses, FYI.

**Comment by anacrolix** [comment]
I guess you read the long comment on why that's there. It only seems necessary with one particular TV, I'm guessing the rest works for you. A shame your device isn't sending a UserAgent either, so I can differentiate these broken clients.

**Comment by anacrolix** [comment]
If you could send me some of the logs you get, from the code that is now executing as a result of your code change, that'd help immensely. In the meanwhile I think I'll plan to make the change you made the default, since most TVs seem to implement evening correctly.

**Comment by mdempsky** [comment]
I should be able to collect some logs tonight.  Is there anything in particular you're interested in?  Just the stdout output with -logHeaders?

**Comment by anacrolix** [comment]
Yes I think logHeaders for starters. I'm interested in what's occurring in event subscription for your device. I take it that with the change you've made, everything else is also working nicely? Seeking/thumbnails/and possibly transcoding if you're utilizing that?

**Comment by mdempsky** [comment]
Yeah, no problems so far since making that change, but I've only tried it a couple times.  Seeking works, but I'll have to check about thumbnails and transcoding.

**Comment by mdempsky** [comment]
Sorry for the delays.  Here are the dms logs from watching a video on my TV:

```
http://shinobi.dempsky.org/~matthew/misc/dms-logs.txt
```

In case you're interested, it's from browsing and playing the set of 512KB MPEG4 videos from https://archive.org/details/FinalFantasy2_356.

Seeking works, but I'm not noticing any thumbnails.  In the TV's folder view, the files are represented by generic video file icons.  (For comparison, the Sonic VGC icon does show up for the main folder; but even with Twonky, I don't think I've ever seen thumbnails.)

File doesn't seem to require transcoding (I don't see ffmpeg running at least).  I had a copy of the .ogv file available too (which I expected might need transcoding because of Theora+Vorbis), but it doesn't show up in the file browser.

**Comment by mdempsky** [comment]
Oops, thumbnails _do_ work once I install the ffmpegthumbnailer package.  (I knew from README.rst that I needed the ffprobe/avprobe commands from ffmpeg, but I didn't realize thumbnailing required another package.)

**Comment by anacrolix** [comment]
It's appalling how media device vendors lock down the software on their devices. Their clients are often garbage, can't be upgraded or switched out.

This one really inspires confidence:

Friendlyname.dlna.org: LG DLNA DMC v0.1

Most of them are some poorly supported Linux client or incomplete framework that's been shoehorned onto their hardware. ಠ_ಠ

</rant>

**Comment by anacrolix** [comment]
You said an ogv didn't show up in the browser, what is the output if you run `go run play/mime.go blah.ogv` in the project source folder?

**Comment by mdempsky** [comment]
```
$ go run play/mime.go FinalFantasy2_356_part01.ogv     
application/ogg
```

**Comment by anacrolix** [comment]
Could you add 

```
    if err := mime.AddExtensionType(".ogv", "video/ogg"); err != nil {
        panic(err)
    }
```

In func init, ./dlna/dms/dms.go:294. Then go run play/mime.go FinalFantasy2_356_part01.ogv  should return "video/ogg".

What OS are you on?

Thanks

**Comment by mdempsky** [comment]
I'll try that tonight.  I'm using OpenBSD.

**Comment by mdempsky** [comment]
With that mime.AddExtensionType change, the .ogv file shows up in the file browser, but the TV gives a "This file is invalid." error when I try to watch it.

**Comment by anacrolix** [comment]
Thanks for the report. I'll close this issue, the original problem is solved.
