### ISSUE TITLE
.ogv file not being transcoded

### ISSUE THREAD

**Issue by mdempsky** [anacrolix/dms#33]
Split from issue #32: FinalFantasy2_356_part01.ogv is visible in my TV's file navigation view, but selecting it gives a "This file is invalid." error.  My expectation from the README is that dms should use ffmpeg to transcode the video to codecs that my TV understands.

**Comment by anacrolix** [comment]
Can you confirm if any other files are transcoding successfully? This one could be difficult: It's basically guess work to determine what codecs TVs support, and whether they can successfully select the right transcode offered. The list of pre-cooked ones are in var transcodes in ./dlna/dms/dms.go. If you think your TV is picking the wrong one you can try commenting some of them out, or tweaking their parameters.

**Comment by anacrolix** [comment]
@mdempsky, any update?

**Comment by mdempsky** [comment]
Sorry, no update. I haven't used dms for a while.

I'll reopen if I get around to trying this again and it still presents an issue.

Thanks.
