### ISSUE TITLE
srt file support without transcoding 

### ISSUE THREAD

**Issue by hemantmits** [anacrolix/dms#35]
Does dms support srt file over dlna without transcoding ?
I tried dms on my rpi 2 but its not sending subtitle to my LG tv.
Video works fine.

**Comment by anacrolix** [comment]
I haven't worked on that. I believe there are ways to advertise srt files to the player, or you can transcode them "hard sub" style, but you'd have to tinker with that. I'd definitely accept contributions that implement this.

**Comment by hemantmits** [comment]
I would like to implement subtitle support but dont know where to start :(.
Is there any specification or some doc which I can referrer to implement it ? 
I know minidlna supports it so it should be possible in dms also.

**Comment by anacrolix** [comment]
It's definitely possible. I don't have access to a suitable DNLA player anymore that would allow me to test an implementation for robustness.

This guy nails it: http://superuser.com/a/645519/15896

I find no useful mention of subtitles in any specs I have. It seems it's player dependent, which defeats the purpose of having a spec in the first place.

**Comment by anacrolix** [comment]
Your best bet it would seem is to ensure the SRT file is exposed, or readable from the server. Most schemes that have this working for external subtitles seem to rely on the name matching minus the extension. This convention is also used by non-DLNA players. I don't believe DMS currently exposes SRTs by default, you could start by adding an exception for those files. That occurs here: https://github.com/anacrolix/dms/blob/master/dlna/dms/cds.go#L57

**Comment by tYYGH** [comment]
Why not stream a mkv containing the original video _and_ the subs? (so no transcoding at all)

**Comment by anacrolix** [comment]
Yes that will put all the responsibility on the player, which is a smart work around (assuming your player supports it).

**Comment by tYYGH** [comment]
mkv is the standard being used for the official DivX Plus HD format.
(See my article about that: http://yalis.fr/cms/index.php/post/2015/04/07/Create-a-DivX-Plus-HD-video-file-on-Linux )
So chances are that most “modern” players (my Marantz is from 2010) recognize it.

**Comment by abdullah2993** [comment]
@anacrolix The mime type of a `srt` file is essentially `text/plain` would it be fine to to just use extension for filtering out subtitle files?

**Comment by anacrolix** [comment]
@hemantmits @tYYGH would you be able to try out and/or comment on https://github.com/anacrolix/dms/pull/79?
