### ISSUE TITLE
proposed precompiled Binaries / compilation error on Qnap NAS

### ISSUE THREAD

**Issue by nephaste** [anacrolix/dms#39]
Hi thanks for this project looks great

will be nice to propose the precompiled Binary released.. (ARMv5, ARMv7, x86, x64..)
i basically try to compiled it for Qnap NAS but i am stuck with Go

```
export GOPATH=/share/GO-PROJECT
 [~] # go get github.com/anacrolix/dms
 # github.com/anacrolix/dms/dlna/dms
 /share/GO-PROJECT/src/github.com/anacrolix/dms/dlna/dms/cds.go:86: undefined: ffprobe.FfprobeUnavailableError

```
not sure where is my mistake..

I am using Go v1.7.5

**Comment by anacrolix** [comment]
Thanks for the report, I think I may have forgotten to push something, I'll let you know shortly.

**Comment by nephaste** [comment]
sure let me know ...

**Comment by anacrolix** [comment]
Someone made a PR that fixes this.

**Comment by anacrolix** [comment]
Also I merged it.

**Comment by nephaste** [comment]
Thanks a lot .. it fixed the issue

**Comment by anacrolix** [comment]
No problem. I hope you find the project useful.
