### ISSUE TITLE
ssdp not advertising on Solaris

### ISSUE THREAD

**Issue by stonedonajax** [anacrolix/dms#42]
Just tried making a build for Solaris (NexentaStor) and the SSDP isn't listening to advertise it on the network.

Looks like the flags aren't correct, but if I comment out the flag checks, I get:

`19:05:15 dms.go:190: error creating ssdp server on e1000g0: listen udp 239.255.255.250:1900: option not supported by protocol`

This issue is just a placeholder while I figure out where the problem is (hopefully with the OS).

**Comment by iamacarpet** [comment]
After some investigation, it looks like net.ListenMulticastUDP doesn't work on Solaris.

I found another method using golang.org/x/net/ipv4 that does work, with a quick commit here showing the method: https://github.com/iamacarpet/dms/commit/22af1fe7642c97eed27d0a1e9102a6bc267b62af

I won't submit a PR as it isn't something this repo is doing wrong, it feels more like the Go net.ListenMulticastUDP is broken, so I've opened a ticket for the language at golang/go#20898

p.s. thanks for the great work @anacrolix 👍

**Comment by anacrolix** [comment]
Thank you both for your efforts.

**Comment by anacrolix** [comment]
Do you want to take another pass at this @iamacarpet ? I have a suspicion this will fix the Windows issues I mentioned in https://github.com/anacrolix/dms/issues/46#issuecomment-356272761.

**Comment by anacrolix** [comment]
Thanks @iamacarpet. @stonedonajax, this looks like it should be fixed in Go 1.10+.
