### ISSUE TITLE
One-use anonymous functions

### ISSUE THREAD

**Issue by Adirelle** [anacrolix/dms#52]
More a question than an issue: there is a lot of these constructs through the code base:

https://github.com/anacrolix/dms/blob/ba875871488470b101fc766dadfcf86c5242638a/dlna/dms/dms.go#L474

This does not seem very "go-ish" (idiomatic to go, would say the purists). What is the purpose of this construct ? Where does this come from ? Javascript ?

**Comment by anacrolix** [comment]
No, it's from the lambda calculus. Here it's used to produce a value without cluttering the scope and naming the function.
