### ISSUE TITLE
Create Automated Build on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [anacrolix/dms#69]
Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add another packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags automatically from git tags & branches.

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags. Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons.

Since #68 is in, just a free Docker Hub account and a quick setup would do. Ping me if you need help.

**Comment by anacrolix** [comment]
I can't figure out how to trivially set this up without giving Docker access to my private repos.

**Comment by pataquets** [comment]
Fair enough. I tried to figure it out myself some time ago, but failed.
How about the brand new [GitHub Container Registry](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry)?
I've already run some public images pulled from it (not my projects) and works well. Not used yet, but I'll get back to you as soon I learn/start to use it, unless you beat me at it.
Just wanted to let you know.

**Comment by anacrolix** [comment]
Sounds great @pataquets, let me know when you have more.

**Comment by gaiaz-iusipov** [comment]
I believe you can grant access only for public repositories

![image](https://user-images.githubusercontent.com/329071/121271253-f76d8c00-c8cb-11eb-9a6c-deb510bd0f01.png)

**Comment by anacrolix** [comment]
I think we can consider this closed by #97 .
