### ISSUE TITLE
Does not work with Kodi

### ISSUE THREAD

**Issue by tekdoc** [anacrolix/dms#70]
I am not getting any errors but Kodi just does not seem see the server. ReadyMedia (formerly MiniDLNA) works fine so I know my Kodi setup and network are not the problem. Any thoughts on troubleshooting?

**Comment by anacrolix** [comment]
You might try with some of the debugging flags to the main binary. More than likely it will be some SSDP or device description incompatibility.

**Comment by halfwit** [comment]
Testing and working fine with VLC, Roku

**Comment by anacrolix** [comment]
@halfwit thanks. I take it you have not tested with Kodi?

**Comment by halfwit** [comment]
I'm going to test it today, sorry for the delay. Haven't had my server up in a while

**Comment by halfwit** [comment]
So yes, this doesn't work at all with Kodi. Over the next while I'll try to get to the bottom of this (as I'm using it as my main DLNA server, and have a few Kodi boxes)

**Comment by briddarobert** [comment]
This seems to have been fixed. It works perfectly for me with Kodi v20.2.0

**Comment by anacrolix** [comment]
Thanks!
