### ISSUE TITLE
Can it run in the environment without go installed?

### ISSUE THREAD

**Issue by dylc5190** [anacrolix/dms#71]
I get this module in a container and save the package in a mounted directory of the host. When I run dms in the host which does not have go installed, the error goes like this:
**bash: ./dms: No such file or directory**

I don't what file it is looking for?

**Comment by anacrolix** [comment]
It should work without Go installed. It's more likely that you don't have the executable bit set, or something else OS-related for executing arbitrary binaries (say you've compiled it for the wrong OS or arch for example).

**Comment by dylc5190** [comment]
I compiled a simple helloworld program in the same container and it works fine in the host. What file should I check to adjust the configuration?

**Comment by dylc5190** [comment]
The output of ldd gave me a hint that I don't have musl-dev installed in the host. It can run now. Thanks.

**Comment by anacrolix** [comment]
Thank you for following up with the solution!
