### ISSUE TITLE
Can it cast to Chromecast audio directly?

### ISSUE THREAD

**Issue by dylc5190** [anacrolix/dms#72]
Can it cast to Chromecast audio directly? I only find one option forceTranscodeTo that is related to Chromecast but this seems not its purpose.

**Comment by anacrolix** [comment]
I believe that Chromecast they have their own protocol for initiating sessions. Chromecast does not to my knowledge allow browsing DMS/UPnPAV servers on the network, even thought it uses SSDP to advertise itself. So I don't think `dms` will currently support this use case. There might be others that are more immersed in this space than me at the moment, I haven't worked on this project for a long while.

**Comment by dylc5190** [comment]
Thank you. I found some projects that implement protocols to communicate with Chromecast. Maybe they can solve my problem.
