### ISSUE TITLE
Path must be absolute

### ISSUE THREAD

**Issue by eexpress** [anacrolix/dms#82]
when i run dms without para, i got this message.
so i 
```
alias dms='/usr/bin/dms -path "`pwd`"'
```
then it works.

Does anacrolix-dms not deal with unicodes in path?

**Comment by anacrolix** [comment]
Sorry, what is para?

**Comment by eexpress** [comment]
sorry, it means arguments and parameter.

**Comment by anacrolix** [comment]
I suspect you are on version 1.1 or lower. Could you upgrade to v1.2 or greater?

**Comment by ebustos** [comment]
After having the same issue with 1.1 (debian package), I can confirm that 1.2 doesn't have this issue anymore.

**Comment by anacrolix** [comment]
Thanks @ebustos .
