### ISSUE TITLE
grep not works on usage message

### ISSUE THREAD

**Issue by whoizit** [anacrolix/dms#92]
`$ dms -h | grep -i trans`

**Comment by anacrolix** [comment]
I think the Go standard library stupidly reports usage to os.Stderr. I think you can override it for the help case. PR welcome!

**Comment by mathieu-aubin** [comment]
@whoizit try redirecting stderr to stdout in order to capture it via pipe, like so:

`dms -h 2>&1 | grep -i trans`

**Comment by anacrolix** [comment]
I can probably fix this now, I'll look into it.

**Comment by anacrolix** [comment]
I don't think it's worth fixing. I would consider switching to https://github.com/anacrolix/bargle/tree/ng or https://github.com/anacrolix/tagflag, both of which correctly output usage to stdout, but they're probably unfamiliar to contributors and not worth the effort as argument parsing in this repo is very straightforward. There are enough apps out there that already incorrectly output usage to stderr too, so it's a common pattern people expect.

When this repo does eventually switch to a better command line parsing implementation, I expect this will be fixed at the same time.
